name: Publication quotidienne Facebook

on:
  schedule:
    # Exécution tous les jours à 10:00 UTC
    - cron: '0 10 * * *'
  # Permet l'exécution manuelle depuis l'interface GitHub
  workflow_dispatch:

jobs:
  post_to_facebook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v3
      
    - name: Configuration de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install openai requests python-dotenv facebook-business pillow
        
    - name: Création du répertoire images
      run: mkdir -p images
      
    - name: Création du fichier .env
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env
        echo "FB_ACCESS_TOKEN=${{ secrets.FB_ACCESS_TOKEN }}" >> .env
        echo "FB_PAGE_ID=${{ secrets.FB_PAGE_ID }}" >> .env
      
    - name: Exécution du script de publication
      run: python facebook_autopost.py
    
